### ISSUE TITLE
Folder structure changes with downloaded plugins

### ISSUE THREAD

**Issue by anic17** [Batch-Man/BatCenter#2]
When you download some plugins, all directories get extracted to root ``/plugins`` dir. It can make errors when using dependencies.

**Comment by TheKvc** [comment]
This issue can only occur - when the plugin uses "Static paths" inside the code for dependencies. but, as per my experience, most of the times dependencies are included as following in batch projects:

1. In the same folder as the script.
2. The path to dependencies is included in the 'PATH' variable.

so, in both of the above cases, things should work fine after you install a plugin in the system using BatCenter.

Although, for keeping the folder structure of the downloaded plugin, I will add a parameter "-get" - which can download the plugin to the current folder or the desired location.
